// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Xenko Shader Mixin Code Generator.
// To generate it yourself, please install Xenko.VisualStudio.Package .vsix
// and re-save the associated .xkfx.
// </auto-generated>

using System;
using Xenko.Core;
using Xenko.Rendering;
using Xenko.Graphics;
using Xenko.Shaders;
using Xenko.Core.Mathematics;
using Buffer = Xenko.Graphics.Buffer;

namespace Xenko.Rendering
{
    public static partial class ImGuiShaderKeys
    {
        public static readonly ValueParameterKey<Matrix> proj = ParameterKeys.NewValue<Matrix>();
        public static readonly ObjectParameterKey<Texture> tex = ParameterKeys.NewObject<Texture>();
        public static readonly ObjectParameterKey<SamplerState> TexSampler = ParameterKeys.NewObject<SamplerState>();
    }
}
